---
- name: Create our container
  hosts: localhost
  tasks:
    - docker_container:
        name: hadoop-solr
        image: prashanthmacys/hadoop-solr:latest
        command: ["sleep", "1d"]

- name: Example play
  hosts: hadoop-solr
  roles:
    - name: "docker-role"
