---
- name: Create our container
  hosts: localhost
  tasks:
    - docker_container:
        name: hadoop-solr 
        image: prashanthmacys/hadoop-solr
        command: ["sleep", "1d"]

- name: Example play
  hosts: example-play
  roles:
    - name: "docker-role"
